### PR TITLE
Removed PI and TWO_PI from defs.hpp.in

### PR DESCRIPTION
**Pull request by nmsriram**
## PR Summary
The definition of PI in defs.hpp.in is superfluous and we should be using M_PI.

I've removed PI and TWO_PI from src/defs.hpp.in and removed the use of PI from example/advection/advection_package.cpp

## PR Checklist

- [x] Code passes cpplint
- [x] N/A New features are documented.
- [x] N/A Adds a test for any bugs fixed. Adds tests for new features.
- [x] Code is formatted

### CODE REVIEW

**Comment by AndrewGaspar** [comment]
@jdolence Is this change good to merge?

**Comment by jdolence** [comment]
do we need to trigger the CI?

**Comment by AndrewGaspar** [comment]
I think it's running.

**Comment by AndrewGaspar** [comment]
@nmsriram I think this just needs a simple conflict resolved - move the deletions to `config.hpp.in`.

**Comment by nmsriram** [comment]
Will replace with a different pull request.

**Pull request closed without merging**
