### PR TITLE
Clean up cpplint issues

### LINKED ISSUE #93: Make cpplint happy
cpplint has a lot of complaints about our style. I will fix these

### PR DESCRIPTION
**Pull request by jlippuner**
Clean up the code to fix all cpplint issues. This fixes #93. I also tried to make the `#include` list uniform across the code base.

Introduced `src/parthenon_mpi.hpp` that selectively includes `<mpi.h>` depending on the macro. I moved this into a separate file because the construct
```
#ifdef MPI_PARALLEL
#include <mpi.h>
#endif
```
showed up in a bunch of places. The issue with that construct is that one has to be careful that `defs.hpp` gets included first where `MPI_PARALLEL` is defined (if MPI is enabled). So to avoid the issue that some files might think MPI is disabled because the above construct is used to early in the include sequence, or `defs.hpp` (or a header that includes it) is not included, I decided to make `parthenon_mpi.hpp` that makes sure `defs.hpp` is included first.

Should be squashed before merging.

## PR Checklist

- [x] Code passes cpplint (yes, NOW it does :D)
- [x] New features are documented. (no new features)
- [x] Adds a test for any bugs fixed. Adds tests for new features. (no new features or bug fixes)

### CODE REVIEW

**Comment by AndrewGaspar** [comment]
Can you rebase this on master now that the formatting change is merged?

**Comment by jlippuner** [comment]
Yup, doing this right now

**Comment by jlippuner** [comment]
@AndrewGaspar this is ready to be merged now (assuming CI with cpplint passes)

**Comment by jdolence** [comment]
everything looks good.  pulling the trigger.

**Pull request merged**
